version: '2.4'
services:
  relearn_mysql_dev:
    container_name: 'relearn-mysql-dev'
    image: 'mysql'
    env_file:
      - .env
    ports:
      - '33060:3306'
  mailcatcher:
    container_name: mailcatcher
    image: dockage/mailcatcher
    expose:
      - 1080
      - 1025
    ports:
      - 1080:1080
      - 1025:1025
